version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  web:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
